# Generated by Django 4.2.6 on 2023-10-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('room_types', models.CharField(max_length=200)),
                ('services', models.TextField()),
                ('photo', models.ImageField(upload_to='hotels_photos/')),
            ],
        ),
    ]
