# Generated by Django 4.2.6 on 2023-10-10 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Visit', '0003_food_remove_restaurant_address_restaurant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='event_photos/')),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='lieux_de_loisirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='lieux_de_loisirs_photos/')),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(upload_to='service_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='TouristSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='sites_touristiques_photos/')),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='adress',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='services',
        ),
        migrations.AddField(
            model_name='hotels',
            name='stars',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visit.service')),
            ],
        ),
        migrations.CreateModel(
            name='bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('stars', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='bar_photos/')),
                ('boissons', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visit.service')),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Visit.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Visit.service'),
            preserve_default=False,
        ),
    ]
