# Generated by Django 4.2.6 on 2023-10-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0005_hospital_province_quartier_shop_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='quartier',
        ),
    ]
