# Generated by Django 4.2.6 on 2023-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0006_delete_province_delete_quartier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=300)),
                ('nom_court', models.CharField(max_length=30)),
                ('est_ieee', models.BooleanField(default=False)),
                ('ville', models.CharField(max_length=100)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('url_site', models.URLField(blank=True, default='')),
            ],
        ),
    ]
