# Generated by Django 4.2.6 on 2023-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0007_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_creation', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='est_ieee',
            new_name='organiserpar',
        ),
    ]
