# Generated by Django 4.2.6 on 2023-10-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0008_culture_rename_est_ieee_conference_organiserpar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
                ('pasteur_principal', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='eglise_photos/')),
                ('nombre_membres', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='photo',
            field=models.ImageField(default=1, upload_to='conference_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='culture',
            name='photo',
            field=models.ImageField(default=1, upload_to='culture-gakondo_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='photo',
            field=models.ImageField(default=1, upload_to='Hopital_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.ImageField(default=1, upload_to='shop_photos/'),
            preserve_default=False,
        ),
    ]
