# Generated by Django 4.2.6 on 2023-10-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0009_eglise_conference_photo_culture_photo_hospital_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eglise',
            name='nombre_membres',
        ),
    ]
