# Generated by Django 4.2.6 on 2023-10-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0010_remove_eglise_nombre_membres'),
    ]

    operations = [
        migrations.AddField(
            model_name='eglise',
            name='heures_de_culte',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
