# Generated by Django 4.2.6 on 2023-10-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0011_eglise_heures_de_culte'),
    ]

    operations = [
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='transport_photos/')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
